baseURL = "https://jeongyoonyang.github.io/"
languageCode = "en-us"
title = "My Portfolio"

theme = "hugo-story"

contentDir    = "exampleSite/content"
staticDir     = "exampleSite/static"
layoutDir     = "exampleSite/layouts"
dataDir       = "exampleSite/data"
archetypeDir  = "exampleSite/archetypes"
